# CONTENT_TYPES = {
#     "Short Story": "a brief fictional narrative typically focusing on a single plot, limited characters, and a concise narrative arc",
#     "Poem": "a piece of writing that expresses feelings, ideas, or observations through rhythmic and often rhyming language",
#     "Article": "an informative piece of writing that presents objective information on a specific topic, typically for publication in a newspaper or magazine",
#     "Essay": "a focused piece of writing that develops an argument or narrative based on evidence, interpretation, and analysis",
#     "Blog Post": "an informal, conversational-style piece of writing typically published on a website or blog, often expressing personal opinions or experiences",
#     "News Report": "an objective account of current events, typically following the inverted pyramid structure and answering the who, what, when, where, why, and how",
#     "Product Review": "a critical evaluation of a product or service, discussing its features, benefits, drawbacks, and overall value",
#     "Tutorial": "a step-by-step guide that teaches readers how to perform a specific task or use a particular tool or technology",
#     "Script": "a written work containing dialogue, stage directions, and other instructions for a play, film, or broadcast",
#     "Speech": "a formal address or discourse delivered to an audience, often persuasive or inspirational in nature",
#     "Research Paper": "a detailed exploration of a specific topic, presenting original research or analysis and typically including citations of other scholarly works",
#     "Business Proposal": "a document that outlines a business idea or project, typically including market analysis, financial projections, and implementation plans",
#     "Press Release": "an official statement issued to news media providing information on a particular matter",
#     "White Paper": "an authoritative report or guide that informs readers concisely about a complex issue and presents the issuing body's philosophy on the matter",
#     "Case Study": "an in-depth examination of a particular subject, such as a person, group, place, event, organization, or phenomenon",
#     "Personal Narrative": "a story from one's life experiences, often reflecting on personal growth or significant events",
#     "Technical Manual": "a document containing instructions for installation, operation, use, maintenance, and product features of a device, machine, or software",
#     "Travel Guide": "an informative piece that provides details about a specific location, including attractions, accommodations, and cultural insights",
#     "Recipe": "a set of instructions for preparing a particular dish, including ingredients, quantities, and cooking methods",
#     "Scientific Abstract": "a brief summary of a research article, thesis, review, or any in-depth analysis of a particular subject",
#     "Social Media Post": "a short, engaging piece of content designed for platforms like Twitter, Facebook, or Instagram",
#     "Email Newsletter": "a regularly distributed email publication that is generally about one main topic of interest to its subscribers",
#     "FAQ": "a list of frequently asked questions and their answers, typically about a specific topic, product, or service",
#     "Biography": "an account of someone's life written by someone else, typically chronologically detailing significant events and achievements",
#     "Memoir": "a historical account or autobiography written from personal knowledge or special sources",
#     "Listicle": "an article structured as a list, often with brief descriptions or explanations for each item",
#     "Opinion Piece": "an article presenting the author's personal stance on a particular subject, often published in newspapers or magazines",
#     "Product Description": "a marketing copy that explains the features and benefits of a product",
#     "Grant Proposal": "a formal document that outlines a project or research idea and requests funding from an organization or institution",
#     "Book Review": "a critical evaluation of a book, discussing its content, style, and merit",
#     "Podcast Script": "a written guide for an audio program, including spoken content, sound effects, and music cues",
#     "Infographic Text": "concise, informative text designed to accompany visual data or graphics",
#     "Cover Letter": "a document sent with a job application explaining the applicant's credentials and interest in the position",
#     "Executive Summary": "a brief document that summarizes a longer report or proposal, highlighting key points for quick review",
#     "User Guide": "a technical communication document that assists people in using a particular system or product",
#     "Marketing Copy": "persuasive writing designed to promote a product, service, or brand and encourage action from the reader",
#     "Legal Document": "a formal written paper that states and explains a legal agreement, such as a contract, will, or deed",
#     "Research Abstract": "a brief summary of a research project, typically including the research question, methodology, findings, and conclusions",
#     "Film Review": "a critical analysis of a movie, discussing its plot, acting, direction, cinematography, and overall quality",
#     "Eulogy": "a speech or piece of writing that praises someone or something highly, typically someone who has recently died",
#     "Mission Statement": "a formal summary of the aims and values of a company, organization, or individual",
# }

CONTENT_TYPES = {
    "Short Story": "short story",
    "Poem": "poem",
    "Email": "email",
    "Blog Post": "blog post",
    "Social Media Post": "social media post",
    "Script": "script",
    "Song Lyrics": "song lyrics",
    "Essay": "essay",
    "Report": "report",
    "Letter": "letter",
    "Instructions": "instructions",
    "Description": "description",
}